---
title: "megaplot"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyr)
library(RColorBrewer)
library(plyr)
library(dplyr)
library(tibble)
library(ggsignif)
library(plotrix)
library(openxlsx)
```

#Read in the data for each library, make individual plot for each library 
#Gateway
```{r}
#read in dfs that I know have the data I need 
GATE <- read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/Gateway/GATE_all_summary_table_seq.csv")
GATE <- filter(GATE,X!="gfpUV")
colnames(GATE) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI","corr_minus_2AP", "corr_plus_2AP","corr_FI", "P1","P2","P3","P4","P5","P6","FULL SEQ")
GATE_seq_try <- GATE[,c("colony","P1","P2","P3","P4","P5","P6","FULL SEQ" )]

ggplot(GATE, aes(x=`corr_minus_2AP`, y=`corr_FI`))+ geom_point(size=3, alpha=1, show.legend = FALSE)+
  labs(title="Gateway Library Repression vs Activity", x="Repression", y="Fold Induction")+
  theme_minimal()
```
#Anchor Exchange
```{r}
AE <-read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/Anchor_exchange/AE_all_summary_table_seq.csv")
AE <- filter(AE,X!="GFPUV")
colnames(AE) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI","corr_minus_2AP", "corr_plus_2AP","corr_FI", "P1.1","P1P4.1","P4.2","P4.3","P4.4","FULL SEQ")
AE_seq <- AE[,c("colony","P1.1","P1P4.1","P4.2","P4.3","P4.4","FULL SEQ" )]

ggplot(AE, aes(x=`corr_minus_2AP`, y=`corr_FI`))+ geom_point(size=3, alpha=1, show.legend = FALSE)+
  labs(title="Anchor Exchange Library Repression vs Activity", x="Repression", y="Fold Induction")+
  theme_minimal()
```
#Loop
```{r}
loop <-read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/Loop/loop_all_summary_table.csv")
loop <- filter(loop,X!="gfpUV")
colnames(loop) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI","corr_minus_2AP", "corr_plus_2AP","corr_FI")

ggplot(loop, aes(x=`corr_minus_2AP`, y=`corr_FI`))+ geom_point(size=3, alpha=1, show.legend = FALSE)+
  labs(title="Loop Library Repression vs Activity", x="Repression", y="Fold Induction")+
  theme_minimal()
```
#Anchor
```{r}
anchor <-read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/Anchor/anchor_all_summary_table.csv")
anchor <- filter(anchor,X!="gfpUV")
colnames(anchor) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI","corr_minus_2AP", "corr_plus_2AP","corr_FI")

ggplot(anchor, aes(x=`corr_minus_2AP`, y=`corr_FI`))+ geom_point(size=3, alpha=1, show.legend = FALSE)+
  labs(title="Anchor Library Repression vs Activity", x="Repression", y="Fold Induction")+
  theme_minimal()
```
#N=6 P4 stem
```{r}
n6p4stem <-read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/n6_P4stem/NONEGn6p4stem_all_summary_table.csv")
n6p4stem <- filter(n6p4stem,X!="GFPUV")
colnames(n6p4stem) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI","corr_minus_2AP", "corr_plus_2AP","corr_FI")

ggplot(n6p4stem, aes(x=`corr_minus_2AP`, y=`corr_FI`))+ geom_point(size=3, alpha=1, show.legend = FALSE)+
  labs(title="N=6 P4 Stem Library Repression vs Activity", x="Repression", y="Fold Induction")+
  theme_minimal()
```
#N=8 P4 stem
```{r}
n8p4stem <-read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/n8_P4stem/n8p4stem_all_summary_table.csv")
n8p4stem <- filter(n8p4stem,X!="gfpUV")
colnames(n8p4stem) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI","corr_minus_2AP", "corr_plus_2AP","corr_FI")

ggplot(n8p4stem, aes(x=`corr_minus_2AP`, y=`corr_FI`))+ geom_point(size=3, alpha=1, show.legend = FALSE)+
  labs(title="N=8 P4 Stem Library Repression vs Activity", x="Repression", y="Fold Induction")+
  theme_minimal()
```
#P3
```{r}
P3 <-read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/P3/P3_all_summary_table.csv")
P3 <- filter(P3,X!="GFPUV")
colnames(P3) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI","corr_minus_2AP", "corr_plus_2AP","corr_FI")

ggplot(P3, aes(x=`corr_minus_2AP`, y=`corr_FI`))+ geom_point(size=3, alpha=1, show.legend = FALSE)+
  labs(title="P3 Library Repression vs Activity", x="Repression", y="Fold Induction")+
  theme_minimal()
ggplot(P3, aes(x=`corr_minus_2AP`, y=`corr_FI`))+ geom_point(size=3, alpha=1, show.legend = FALSE)+
  labs(title="P3 Library Repression vs Activity", x="Repression", y="Fold Induction")+
  theme_minimal()
```
#P1 exchange
```{r}
P1exchange <-read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/P1exchange/P1exchange_all_summary_table.csv")
P1exchange <- filter(P1exchange,X!="gfpUV")
colnames(P1exchange) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI","corr_minus_2AP", "corr_plus_2AP","corr_FI")

ggplot(P1exchange, aes(x=`corr_minus_2AP`, y=`corr_FI`))+ geom_point(color="#C77CFF", size=3, alpha=1, show.legend = FALSE)+
  labs(title="P1 Exchange Library Repression vs Activity", x="-2AP Fluorescence", y="Fold Induction")+
  scale_y_continuous(expand = c(0.25,0))+
  ylim(0,1.5)+
  theme_minimal()
```
#create 1 df with all libraries 
```{r}
library <- rep("A EXCHANGE",nrow(AE))
AE <- cbind(AE,library)
library <- rep("GATEWAY",nrow(GATE))
GATE <- cbind(GATE,library)
library <- rep("LOOP",nrow(loop))
loop <- cbind(loop,library)
library <- rep("ANCHOR",nrow(anchor))
anchor <- cbind(anchor,library)
library <- rep("N6P4STEM",nrow(n6p4stem))
n6p4stem <- cbind(n6p4stem,library)
library <- rep("N8P4STEM",nrow(n8p4stem))
n8p4stem <- cbind(n8p4stem,library)
library <- rep("P3",nrow(P3))
P3 <- cbind(P3, library)
library <- rep("P1EXCHANGE",nrow(P1exchange))
P1exchange <- cbind(P1exchange, library)
plotdf <- rbind(GATE[,c(1:9,17)],AE[,c(1:9,16)],loop,anchor,n6p4stem,n8p4stem,P3, P1exchange)

ggplot(plotdf, aes(x=`corr_minus_2AP`, y=`corr_FI`, color = library))+ geom_point(size=2, alpha=0.5, show.legend = TRUE)+
  labs(title="All Libraries Repression vs Activity", x="-2AP Fluorescence", y="Fold Induction")+
  theme_minimal()
```

```{r}
ggplot(plotdf, aes(x=`corr_minus_2AP`, y=`corr_FI`, color = library))+ geom_point(size=2, alpha=0.5, show.legend = TRUE)+
  scale_x_continuous(trans='log10') +
  labs(title="All Libraries Repression vs Activity", x="Repression", y="Fold Induction")+
  theme_minimal()
ggplot(plotdf, aes(x=`corr_minus_2AP`, y=`corr_FI`, color = library))+ geom_point(size=2, alpha=0.5, show.legend = TRUE)+
  scale_y_continuous(trans='log10') +
  labs(title="All Libraries Repression vs Activity", x="Repression", y="Fold Induction")+
  theme_minimal()
ggplot(plotdf, aes(x=`corr_minus_2AP`, y=`corr_FI`)) + 
  geom_point(size=1, alpha=1,color="blue") +
  labs(title="Each library plot", x="Repression", y="Fold Induction")+
  theme_minimal()+
  facet_wrap(vars(library))
ggplot(plotdf, aes(x=`corr_minus_2AP`, y=`corr_FI`)) + 
  geom_point(size=1, alpha=1,color="blue") +
  labs(title="Each library plot", x="Repression", y="Fold Induction")+
  scale_y_continuous(trans='log10') +
  theme_minimal()+
  facet_wrap(vars(library))
ggplot(plotdf, aes(x=`corr_minus_2AP`, y=`corr_FI`)) + 
  geom_point(size=1, alpha=1,color="blue") +
  labs(title="Each library plot", x="Repression", y="Fold Induction")+
  scale_x_continuous(trans='log10') +
  theme_minimal()+
  facet_wrap(vars(library))
```
#make a big big plot with the bins
```{r}
#read in bins
AEbins <- read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/Anchor_exchange/AE_binning.csv")
colnames(AEbins) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI", "corr_minus_2AP", "corr_plus_2AP", "corr_FI", "REPbin", "FIbin","binvalue","bin")
GATEbins <- read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/Gateway/gateway_binning.csv")
colnames(GATEbins) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI", "corr_minus_2AP", "corr_plus_2AP", "corr_FI", "REPbin", "FIbin","binvalue","bin")
ANCHbins <- read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/Anchor/anchor_binning.csv")
colnames(ANCHbins) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI", "corr_minus_2AP", "corr_plus_2AP", "corr_FI", "REPbin", "FIbin","binvalue","bin")
N6P4bins <- read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/n6_P4stem/n6p4stem_binning.csv")
colnames(N6P4bins) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI", "corr_minus_2AP", "corr_plus_2AP", "corr_FI", "REPbin", "FIbin","binvalue","bin")
N8P4bins <- read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/n8_P4stem/N8P4_binning.csv")
colnames(N8P4bins) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI", "corr_minus_2AP", "corr_plus_2AP", "corr_FI", "REPbin", "FIbin","binvalue","bin")
LOOPbins <- read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/Loop/loop_binning.csv")
colnames(LOOPbins) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI", "corr_minus_2AP", "corr_plus_2AP", "corr_FI", "REPbin", "FIbin","binvalue","bin")
P1EXbins <- read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/P1exchange/P1exchange_binning.csv")
colnames(P1EXbins) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI", "corr_minus_2AP", "corr_plus_2AP", "corr_FI", "REPbin", "FIbin","binvalue","bin")
P3bins <- read.csv("~/Downloads/Expression_platform_project/expression_platform_files/analysis/output_files/P3/P3_binning.csv")
colnames(P3bins) <- c("colony","-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI", "corr_minus_2AP", "corr_plus_2AP", "corr_FI", "REPbin", "FIbin","binvalue","bin")
megabin <- rbind(AEbins,GATEbins, ANCHbins, N6P4bins, N8P4bins, LOOPbins, P1EXbins, P3bins)
ggplot(megabin, aes(x=`corr_minus_2AP`, y=`corr_FI`, color = `bin`))+ geom_point(size=2, alpha=0.5, show.legend = TRUE)+
  labs(title="All Libraries Repression vs Activity Bins", x="-2AP Fluorescence", y="Fold Induction")+
  theme_minimal()
```

