---
title: "ava_library"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyr)
library(RColorBrewer)
library(plyr)
library(dplyr)
library(tibble)
library(ggsignif)
library(plotrix)
library(openxlsx)
```
## Creating the function to remove outliers based on Interquartile range
```{r}
removeOut <- function(distribution, bounds=1.5, na.rm = TRUE) {
 Q <- quantile(distribution, probs=c(.25,.75), na.rm=TRUE) 
 #finds the 25th and 75th percentile of the distribution, excluding NAs
 iqr <- IQR(distribution, na.rm=TRUE)
 #difference between 75th and 25th quartile=interquartile range
 upperBound <- Q[2]+bounds*iqr
 #upper bound of the values is 75th quartile + 1.5*(interquartile range) note: that 1.5 can be vaired by changing bound
 lowerBound <- Q[1]-bounds*iqr
 #upper bound of the values is 25th quartile - 1.5*(interquartile range)
 eliminated <- c(distribution < lowerBound | distribution > upperBound)
 #take out the values that are outside of the established bounds note: that 1.5 can be vaired by changing bound
 noteliminatedindex <- which(distribution > lowerBound & distribution < upperBound)
 #index values within the upper and lower bounds
 noteliminatedvalues <- distribution[noteliminatedindex]
 return(noteliminatedvalues)
 #return those values which will be included that are between the upper and lower bounds 
}
```
##Read in csv
```{r}
n6p4stem <- read.csv("022423_avadata.csv")
n6p4stem[n6p4stem == -2] <-NA
#made DFs for rep/exp/FI
n6p4stem_minus <- n6p4stem[n6p4stem == '(-)',]
n6p4stem_plus <- n6p4stem[n6p4stem == '(+)',]
n6p4stem_FI <- n6p4stem[n6p4stem == 'FI',]
```
##Remove outliers 
```{r}
noOut_n6p4stem_minus.list <- apply(n6p4stem_minus[,2:ncol(n6p4stem_minus)], 2, removeOut, na.rm=TRUE)

noOut_n6p4stem_minus_sideways <- plyr::ldply(noOut_n6p4stem_minus.list, rbind)
noOut_n6p4stem_minus <- data.frame(t(noOut_n6p4stem_minus_sideways[-1]))
colnames(noOut_n6p4stem_minus) <- noOut_n6p4stem_minus_sideways[,1]
noOut_n6p4stem_minus_wideform <- cbind(n6p4stem_minus[1:nrow(noOut_n6p4stem_minus),1],noOut_n6p4stem_minus[,1:ncol(noOut_n6p4stem_minus)])
colnames(noOut_n6p4stem_minus_wideform)[1] <- "COLONIES"
long_n6p4stem_minus <- gather(noOut_n6p4stem_minus_wideform, Colony_Name, Fluorescence, -COLONIES)

noOut_n6p4stem_plus.list <- apply(n6p4stem_plus[,2:ncol(n6p4stem_plus)], 2, removeOut, na.rm=TRUE)
noOut_n6p4stem_plus_sideways <- plyr::ldply(noOut_n6p4stem_plus.list, rbind)
noOut_n6p4stem_plus <- data.frame(t(noOut_n6p4stem_plus_sideways[-1]))
colnames(noOut_n6p4stem_plus) <- noOut_n6p4stem_plus_sideways[,1]
noOut_n6p4stem_plus_wideform <- cbind(n6p4stem_plus[1:nrow(noOut_n6p4stem_plus),1],noOut_n6p4stem_plus[,1:ncol(noOut_n6p4stem_plus)])
colnames(noOut_n6p4stem_plus_wideform)[1] <- "COLONIES"
long_n6p4stem_plus <- gather(noOut_n6p4stem_plus_wideform, Colony_Name, Fluorescence, -COLONIES)

noOut_n6p4stem_FI.list <- apply(n6p4stem_FI[,2:ncol(n6p4stem_FI)], 2, removeOut, na.rm=TRUE)
noOut_n6p4stem_FI_sideways <- plyr::ldply(noOut_n6p4stem_FI.list, rbind)
noOut_n6p4stem_FI <- data.frame(t(noOut_n6p4stem_FI_sideways[-1]))
colnames(noOut_n6p4stem_FI) <- noOut_n6p4stem_FI_sideways[,1]
noOut_n6p4stem_FI_wideform <- cbind(n6p4stem_FI[1:nrow(noOut_n6p4stem_FI),1],noOut_n6p4stem_FI[,1:ncol(noOut_n6p4stem_FI)])
colnames(noOut_n6p4stem_FI_wideform)[1] <- "COLONIES"
long_n6p4stem_FI <- gather(noOut_n6p4stem_FI_wideform, Colony_Name, Fluorescence, -COLONIES)

median_n6p4stem_FI<- as.data.frame(apply(noOut_n6p4stem_FI, 2, median, na.rm=TRUE))
median_n6p4stem_minus<- as.data.frame(apply(noOut_n6p4stem_minus, 2, median, na.rm=TRUE))
median_n6p4stem_plus<- as.data.frame(apply(noOut_n6p4stem_plus, 2, median, na.rm=TRUE))

SE_n6p4stem_minus <- std.error(noOut_n6p4stem_minus)
SE_n6p4stem_plus <- std.error(noOut_n6p4stem_plus)

n6p4stem_summary_table <- cbind.data.frame(median_n6p4stem_minus, SE_n6p4stem_minus, median_n6p4stem_plus, SE_n6p4stem_plus, median_n6p4stem_FI)

#sig figs
odd_cols <- c(1,3,5)
even_cols <- c(2,4)
n6p4stem_summary_table[,odd_cols] <- signif(n6p4stem_summary_table[,odd_cols],2)
n6p4stem_summary_table[,even_cols] <- signif(n6p4stem_summary_table[,even_cols],1)
#rename column names
colnames(n6p4stem_summary_table) <- c("-2AP", "-2AP_SE","+2AP", "+2AP_SE", "FI")
#write csv
write.csv(n6p4stem_summary_table,"~/Downloads/Expression_platform_project/expression_platform_files/ava_library/ava_output_021723/2n6p4stem_summary_table.csv", row.names = TRUE)

#remove the switches below the functional cutoff of 2.0
#find the FI median
n6p4stem_summary_table_above2 <- subset(n6p4stem_summary_table, FI>=2.0)
#write csv
write.csv(n6p4stem_summary_table_above2,"~/Downloads/Expression_platform_project/expression_platform_files/ava_library/ava_output_021723/2n6p4stem_summary_table_above2.csv", row.names = TRUE)
#write excel
write.xlsx(n6p4stem_summary_table,"~/Downloads/Expression_platform_project/expression_platform_files/ava_library/ava_output_021723/2n6p4stem_summary_table.xlsx", rowNames = TRUE)
write.xlsx(n6p4stem_summary_table_above2,"~/Downloads/Expression_platform_project/expression_platform_files/ava_library/ava_output_021723/2n6p4stem_summary_table_above2.xlsx", rowNames = TRUE)
```
